### ISSUE TITLE
Support hive style listing / partitioning

### ISSUE THREAD

**Issue by tshauck** [datafusion-contrib/arrow-zarr#13]
Currently the reader only really works w/ a single file. The end state that would resolve issue would be:

1. support for "listing tables"
2. support for hive style partitioning, where predicates influence the files scanned and the table is augmented with the partition information

**Comment by maximedion2** [comment]
So, somewhat related to this, my understanding is that there are 2 reasons why a "table schema" can differ from the "file schema", the first one is partitions (e.g. `some_variable=123` as a directory introduces the column `some_variable`, that is not contained in the files), the second one is if some files contain a given column but others don't (and that column gets initialized as null in the data for the files that don't have it).

Assuming that this is correct, I was thinking we don't handle the latter for now? Since we directly work on zarr stores, that situation can't happen without partitions, but if say we have `some_variable=123` and `some_variable=456`, we _could_ make it so that if one of the 2 directories is missing some columns from the other one, we handle that with null values, but we could also just make that throw an error? Do you think there are use cases for zarr where a partition directory wouldn't contain all the columns (which to be clear are actually zarr arrays here)?

**Comment by tshauck** [comment]
For the second one, schema mismatches, I think it's somewhat context specific. Unioning the schemas is certainly an option and I've seen in done in more in traditional DW use-cases, but to your point, it's not clear to me how much that'd actually happen in practice. There's also cost associated with doing those checks, especially w/ a remote store.

**Comment by maximedion2** [comment]
Right, that's what I was thinking, combining schemas isn't free, both in terms of cost at run time and in terms of code complexity. I guess I'll start with hive style partitioning and I can revisit combining different schemas later.

**Comment by maximedion2** [comment]
So, I started writing the code for this, and then I started thinking about exactly what the folder structure should look like, and then I thought, we should basically follow the standards for zarr groups, right? So you've got your data.zarr root, then you create a group called "var=123", another one called "var=456", etc..., then under "var=123" you can create a group called "other_var=abc", etc... and then under var=123/other_var=abc/ we would have the different arrays listed, just like we do now at the root? That way the concept of a partition is directly related to an existing zarr concept?

**Comment by maximedion2** [comment]
@tshauck Quick update, I've been mostly done with implementing this for about a week now, but when I run a test, I get an error from pretty deep within datafusion, so I've now spent several days going through datafusion code (admittedly I only have one or 2 hours per day to spend on this these days), if I can't figure out the issue soon I think I'll try pointing the cargo.toml to a local copy of the datafusion repo to make it easier to debug.

**Comment by tshauck** [comment]
@maximedion2 Nice, if you want to push your branch up, I'd be happy to see if I know what the issue could be.

**Comment by maximedion2** [comment]
I actually fixed that a couple days after I mentioned it. I still have a few minor things to fix with file vs table schemas when partitions are included, but I'm getting close I think. We just moved to a new house and I got really busy with that so I haven't worked on this for several days but I'm back on it now.
