### ISSUE TITLE
Where are testing files?

### ISSUE THREAD

**Issue by tshauck** [datafusion-contrib/arrow-zarr#2]
Hi, I was really excited to see this nascent project as I'm interested in using zarr with arrow/datafusion myself. I realize it's early, so I started a PR to do linting, update the cargo.toml to use the same compression library for lzma as datafusion proper, etc. You can find it here: https://github.com/datafusion-contrib/arrow-zarr/compare/main...tshauck:tweaks-to-zarr?expand=1

As part of that I went to run the tests and found that I'm missing the test files which I guess should exist at `testing/data/zarr` -- where are these? I checked https://github.com/apache/arrow-testing/tree/master but didn't find anything relevant.

Thanks

**Comment by tshauck** [comment]
Hi @maximedion2, I thought I'd tag you just in case given your recent work on this repo, perhaps you could help. Thanks!

**Comment by maximedion2** [comment]
Hi @tshauck! It's great to have someone else involved with this project. As you said it's very early, and I'm doing this as a personal project (so outside of my working hours), so it's not moving as fast as I'd like it to, but I'm making progress!

Regarding linting and updating the cargo.toml, we might have to hold off on that for a couple weeks, you see I'm refactoring most of the code (already...) because I want to add support for Zarr v3, while still supporting Zarr v2, so making things compatible and uniform is taking a little while, but I made good progress recently, I'm expecting to have something that is worth linting within the next 2 weeks. I appreciate the time you spent doing that, I'll get back to you when we're good to go!

For the tests, you are right they are on my computer right now, but I'm planning on asking someone to create a "testing" repo under `datafusion-contrib`, so that test data can be imported as a submodule in arrow-zarr (or in any other `datafusion-contrib` repo), just like in datafusion proper. Since I'm working on Zarr v3 right now, I'm planning on introducing more tests shortly, and cleaning up the Zarr v2 ones, so I was holding off on that as well, I'm probably going to ask for that repo next week.

My rough timeline, for now, is to wrap up the zarr -> arrow part at some point in March, after which I want to move on to actually implementing the query engine part using datafusion, hopefully I get started around mid-March. I also have other things I'd like to gradually introduce (though I'm probably being way too ambitious), including adding geospatial functionalities (by using an existing Rust crate for the core logic), but that's for later!

**Comment by tshauck** [comment]
That all generally sounds good to me! Once you get the v2/v3 code merged, I can help add the datafusion bits on top (e.g. `FileOpener`, `TableProvider`, etc.) and get the repo into a deployable state. Please do let me know if you get delayed or have other things come up given you're working on this on the side like you mention.

FWIW, I'm coming at this from a microscopy standpoint, so not sure how much overlap there is with geospatial work, but there may be some useful primitives.

**Comment by maximedion2** [comment]
Quick update, I'm more or less done with adding v3 support, I'm adding a few more tests right now and I'll probably ask for that test repo tomorrow. I have a couple more things I want to do before the code is in a stable enough state, I'm expecting to be done next week.

Yeah by "geospatial" I basically mean PostGIS-like queries, which don't necessarily only apply to geographical data, I'd say it's more like geometrical data, so it might be useful for other things as well.

**Comment by maximedion2** [comment]
So, actually, are you familiar with how "readers" are used on the DataFusion side? I looked into it a while ago, and I mostly followed the overall structure of the parquet arrow reader for my work, but I'd like to understand better how the data is processed after it's read. Specifically, the parquet (async) reader (and the zarr reader I wrote) works by implementing `Stream`, and I'm wondering what picks up the results from the stream as they become available.

For context, the reason I'm asking is that while I got something that works (will formalize tests and add more comments tonight most likely), I'm not completely happy with the stream I wrote, it "blocks the thread" due to zarr chunks having to be decompressed, "chunk edges" needing to be handled, other codecs, etc... and I want to understand how much flexibility I have here with what the reader returns.

In any case, let me know if it's something you have some understanding of, from what I remember there was definitely a lot of stuff to look at in DataFusion, it was difficult to find specifically what I was looking for!

Thanks!

**Comment by maximedion2** [comment]
Yeah I think that makes sense, thanks!.

I think I'll push something soon, I've been working on this all by myself, it would be great to have someone else's perspective and see if what I'm doing at least makes some sense (and I greatly appreciate your feedback!). Actually if you don't mind I'll start with a high level view of how I'm planning this? Could provide some context if you take a deeper look in the code.

Basically, from the user's perspective, the reader reads a whole directory, with one or more Zarr arrays in it. Users can provide "columns" to read (by which I mean specific arrays), as well as conditions, but they don't select a particular file. I did that because there's a significant amount of logic that goes into reading different arrays together, to provide record batches that combine them correctly (unlike e.g. parquet files, the different "columns" are stored in different files here). Predicates can be applied to just some of the arrays, to determine if a given chunk for the non-predicate requested arrays needs to be read. So far, hopefully so good, but let me know if anything doesn't make sense.

From the point of view of the user, e.g. DataFusion, I think the reader will _have_ to block at some point. This is because the reader would be responsible for decompression, and handling things that are specific to Zarr file (e.g. edges of incomplete chunks), so there has to be some amount of blocking code in the process, at least I think so. Again, so far hopefully that all makes sense.

Now if we forget the user for now, and only consider the reader by itself, that's where I'm not quite satisfied with what I wrote. The stream logic I currently have mimics what was done for parquet files, which might be fine for parquet, but less so for Zarr which typically has compressed data (BTW do I correctly understand that right now compression is not supported for parquet files?). A future that reads a file is awaited, then the result is passed along to the code for decompression and other data manipulations, then the final result is returned, and a new future is awaited (all within the `Stream` implementation). This might _technically_ be async, but from my (admittedly limited) understanding, this is really not async in practice -- while the future is awaited, there is nothing else to do for the thread, and when the thread has some work to do, we have not yet polled the next future. This might be fine in the bigger picture, it might not be a big issue when considering the actual computations the query engine will run, but part of me doesn't like the idea of producing something that is not efficient by itself and justifying by saying "it's okay it will be used by something computationally heavy".

All that to say that I will probably push something soon, and come back to work on this in a day or 2, just to get things going. Let me know if you think anything I explained above doesn't make sense or just isn't the right approach in your opinion!

**Comment by tshauck** [comment]
I think that makes sense. For the columns, it may require some special code to have datafusion treat a directory as table differently than how it does for parquet (to your point), but it's good if the reader can take a set of columns to read. Datafusion can push that info down from the projection. Same with predicates.

For the reader (the second to last paragraph), again I'm speaking a little off-base without something to look at, but I do wonder if decompression/decoding/etc could be delayed? E.g. for one of my projects, the decoding of binary fields is delayed until they're needed if at all [e.g.](https://github.com/wheretrue/exon/blob/779902943672ce101a07e26ae50ac328af57521f/exon/exon-bam/src/array_builder.rs#L102-L218). Have you done any benchmarking (e.g. via samply) to see the workers are doing?

To your parquet question, I think it does support compression, it's just parquet compresses within the format vs something like CSV.

Anyways, definitely agree it'd be nice for it to be efficient. Hopefully to the extent it isn't we can work to have it climb the ladder.

**Comment by maximedion2** [comment]
Oh, sorry my comment/question wasn't clear, parquet most definitely supports compression, I meant to say that in `arrow-rs`, the parquet readers don't handle it, at least from what I understand (e.g. the logic to only read specific rows after filtering wouldn't work), which is why the way their stream is produced might not be the best approach for a zarr reader.

Well, so I only ever read a chunk if it's needed, as much as possible I avoid reading a file if the corresponding chunks for other variables don't have any values that satisfy a predicate, for example. My understanding is, if a "column" has been requested, and at least some data in a chunk file is needed, then you'd want to read it, decompress it and send that data over to datafusion asap, so that it can start its work while other chunks are being processed.

Basically, the way I think about this (and it's entirely possible I misunderstand some things here) is that while reading a file, you want to let the cpu do some work on the data you sent over up to that point. While you're decompressing a chunk though, the reader will actually block the thread, which is inevitable. The part that I want to improve is that while you're reading a file, I also want to let the cpu work on decompression, which is currently not the case I believe. I haven't done very detailed benchmarks yet, and I've never used samply, I can't really find info on it, what is it? I could definitely use a good tool to help me figure out the best approach here.

In the end, I think I'll merge my work up to now pretty soon, hopefully tonight, and I'll work on a few other things, including the stream optimization, in a separate PR. I also want to get started on the DataFusion part soon, I'm eager to see how that works, so I'll probably move forward with that next week-ish.

Thanks again for your comments!

**Comment by tshauck** [comment]
Here's samply: https://github.com/mstange/samply... but yeah, looking forward to playing around w/ what you've got when you're ready.

**Comment by maximedion2** [comment]
I merged my work from the last few weeks into main, including adding a `test-data` sub-directory (`git submodule update --init` should set everything up). I'm done for now with implementing v3, I think we can move forward with overall formatting. To be clear, you are following the steps under Code Formatting from here, https://github.com/apache/arrow-rs/blob/master/CONTRIBUTING.md, right? I'll start doing that myself soon, but before I do I just want to make sure that that's what you are doing.

Right now the only thing that this supports is reading zarr files into record batches (well, it reads whole directories and processes all the data so that everything is aligned in the record batches) and applying predicates to filter out the data, is there anything you want to test against, just for fun? I've been doing all my testing with dummy data I generate with python packages, it's obviously not a perfect proxy for real applications, so if you have anything you want to try out just let me know (or we can wait until there's more stuff implemented)! Of course feel free to look at the code and provide any feedback, I have a some comments in there, but let me know if you want a summary of how everything is structured for now.

For next steps, there's some good discussions on that task I mentioned this current issue on, regarding async streams and blocking work, I'm gonna take a few days to try out different ways of improving the stream, I'll create a new task for that and post samply outputs there. After that, probably next week, I want to get started on implementing everything in DataFusion, I'll look into it a bit (it's been a while since I looked at it) and then I'll create an issue for us to discuss specifics.

**Comment by tshauck** [comment]
Ok great. W.r.t code formatting, yes, I was basically using that. Arrow/datafusion don't use any exceptions to the default clippy/format rules.

Otherwise, I'll give it a shot soon with. some of my data and let you know how it works. And if you want to make some of the datafusion specific issues that sounds like a good next step to me.

**Comment by tshauck** [comment]
Also, just tried to get the test files, but the submodule points to a repo that doesn't exist yet... https://github.com/datafusion-contrib/test-data/tree/333fb9ac03de3aa471933f03afe29b56e864c0ac

**Comment by maximedion2** [comment]
Oh sorry, I didn't even realize that the repo was private. That's how Andrew Lamb created it, I think he's the owner or something, I don't seem to have full access to settings to make it public, I'll check in the asf channel and ask to make it public, should be good after that.

**Comment by tshauck** [comment]
Sounds good, thanks! You might also ask if he can activate actions for this repo, as I don't think they are yet.

**Comment by tshauck** [comment]
@maximedion2 I made a PR here that we could merge then adopt for this PR going forward: https://github.com/datafusion-contrib/arrow-zarr/pull/4.

**Comment by maximedion2** [comment]
Yeah saw that earlier, sounds good!

So I'm admin on the `test-data` repo now, I made it public, but you'll have to rebase on main before you can run the tests, yesterday I realized that I forgot to change the paths to the test data after I made the repo a submodule, so I merged a fix, https://github.com/datafusion-contrib/arrow-zarr/pull/5/files.

I'm admin on the arrow-zarr repo, so I can look at the github actions. I don't think they're disabled per se, it's just that there's nothing committed yet? I can create a commit directly through github apparently, that will create the `.github/workflow/rust.yml`, I might be able to include some things as I create it, and then we can add more after it's committed? Anything other than linting and running the tests you want to include there?

**Comment by tshauck** [comment]
I actually have that yml file in my PR, so if you wanna merge the PR or add a the file separately either is good with me.

I've also rebased the PR so it should be able to merge w/o conflicts.

**Comment by tshauck** [comment]
I think we're good on this, so I'm gonna close it, thanks!
